//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopCoffee_asp_sqlserver {
    public partial class Cart {
        protected global::System.Web.UI.WebControls.GridView gvCart;
        protected global::System.Web.UI.WebControls.Label lblTotal;
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.TextBox txtPhone;
        protected global::System.Web.UI.WebControls.Repeater rptTables;
        protected global::System.Web.UI.WebControls.HiddenField hfSelectedTableId;
        protected global::System.Web.UI.WebControls.Button btnOrder;
        protected global::System.Web.UI.WebControls.Button btnClear;
    }
}
