//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopCoffee_asp_sqlserver {
    public partial class DatBan {
        protected global::System.Web.UI.WebControls.Repeater rptTables;
        protected global::System.Web.UI.WebControls.DropDownList ddlTables;
        protected global::System.Web.UI.WebControls.TextBox txtBookingTime;
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.Button btnBook;
    }
}
